server:
  port: 8081

spring:  cloud:    config:      server:        git:          uri: https://github.com/ArthurRmz/microservicios-spring-cloud
          search-paths: config-data
  application:
    name: config-service