server:
  port: 8081

spring:  cloud:    config:      server:        git:
          ignore-local-ssh-settings: true
          default-label: master          uri: https://github.com/ArthurRmz/microservicios-spring-cloud.git
          search-paths: config-data
  application:
    name: config-service